### PR TITLE
change star distribution full bar width to 100pr

### PR DESCRIPTION
**Pull request by zanamich**

### CODE REVIEW

**Comment by zanamich** [comment]
@vladshub / @gadinehab ,
This needs to be test inside a dev account to see it doesn't break nothing (and it doesn't..). Once I'll have the OK from you I'll merge it to gh-pages and create a PR in the widget to update the ds version.

**Comment by vladshub** [comment]
@gadinehab please confirm that this looks fine.

**Comment by gadinehab** [comment]
@zanamich didn't find any problems

**Comment by gadinehab** [comment]
@NetanelMoshkovitz ok

**Pull request merged**
