### PR TITLE
feat(SizeCustomField):added size custom field to styles and index.html YO-384

### PR DESCRIPTION
**Pull request by EranAvidor**
JIRA Task: https://jira.yotpo.com/browse/YO-384

Epic PRD: https://jira.yotpo.com/browse/YO-653
Design: https://projects.invisionapp.com/share/92588F9KQ#/screens/114084039

### CODE REVIEW

**Comment by livnekes** [comment]
@gadinehab this is ok

**Comment by EranAvidor** [comment]
@avichay it passed CR and DR but Gadi didn't have time to go through it.
please advice.

**Comment by avichay** [comment]
@EranAvidor we will perform the QA

**Comment by livnekes** [comment]
@NetanelMoshkovitz this is good

**Pull request merged**
