### PR TITLE
add custom fields implementation using table

### PR DESCRIPTION
**Pull request by livnekes**

### CODE REVIEW

**Comment by zanamich** [comment]
@livnekes ,
1. Pls change the custom_fields.scss file name to something more generic related to all email's HTML to come in the future.
2. Pls give a h3 headline to each example you added. (e.g. "Customised Forms - Rating Field - Email version")

Assign it back to me when you're done.

**Comment by zanamich** [comment]
@livnekes pls merge this branch.

**Comment by zanamich** [comment]
@livnekes yotpo_emails.css should move into ds_sass directory

**Comment by livnekes** [comment]
@zanamich can you confirm and merge?

**Comment by livnekes** [comment]
@zanamich ping

**Comment by zanamich** [comment]
@livnekes pls lets decide once and for all what should I do about it. This PR is now almost  1 year old!

**Comment by livnekes** [comment]
@zanamich I think we should delete this. we only use this code in the API.

**Comment by zanamich** [comment]
@livnekes Done.

**Pull request closed without merging**
